#!/usr/bin/env bash
# Function to display information about a subdomain
display_info() {
    local subdomain=$1
    local domain=$2

    # Define IP addresses for subdomains
    case $subdomain in
        "www")
            ip_address="54.210.47.110"
            ;;
        "lb-01")
            ip_address="54.210.47.110"
            ;;
        "web-01")
            ip_address="34.198.248.145"
            ;;
        "web-02")
            ip_address="54.89.38.100"
            ;;
        *)
            echo "Invalid subdomain"
            return
            ;;
    esac

    # Perform DNS lookup for the subdomain
    local result=$(dig +short ${subdomain}.${domain})

    if [ -z "$result" ]; then
        echo "The subdomain ${subdomain} does not exist for ${domain}"
    else
        if [ "$result" == "$ip_address" ]; then
            echo "The subdomain ${subdomain} is a A record and points to ${ip_address}"
        else
            echo "The subdomain ${subdomain} points to an unexpected IP address: ${result}"
        fi
    fi
}

# Function to display information about default subdomains
display_default_info() {
    local domain=$1

    # Default subdomains
    local subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${subdomains[@]}"; do
        display_info $subdomain $domain
    done
}

# Main script

if [ $# -eq 1 ]; then
    # When only the parameter domain is provided
    display_default_info $1
elif [ $# -eq 2 ]; then
    # When passing domain and subdomain parameters
    display_info $2 $1
else
    # Invalid number of arguments
    echo "Usage: $0 domain [subdomain]"
fi

