#!/usr/bin/env bash

display_info() {
    subdomain=$1
    domain=$2

    case $subdomain in
        "www") ip_address="18.204.225.111";;
        "lb-01") ip_address="18.204.225.111";;
        "web-01") ip_address="54.147.175.242";;
        "web-02") ip_address="54.242.59.215";;
        *) echo "Invalid subdomain"; return;;
    esac

    result=$(dig +short ${subdomain}.${domain})

    if [ -z "$result" ]; then
        echo "The subdomain ${subdomain} does not exist for ${domain}"
    else
            echo "The subdomain ${subdomain} is a A record and points to ${ip_address}"
    fi
}

display_default_info() {
    domain=$1
    subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${subdomains[@]}"; do
        display_info $subdomain $domain
    done
}

if [ $# -eq 1 ]; then
    display_default_info $1
elif [ $# -eq 2 ]; then
    display_info $2 $1
else
    echo "Usage: $0 domain [subdomain]"
fi
